# Generated by Django 4.2.5 on 2024-04-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_userresponse_groupclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='response',
            field=models.IntegerField(default=0),
        ),
    ]
